name: note_link
description: "A comprehensive note-taking application with calendar integration, groups, themes and deadlines."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2 # Управление состоянием приложения
  uuid: ^4.0.0+1 # Генерация уникальных идентификаторов
  intl: ^0.19.0 # Локализация и форматирование дат
  table_calendar: ^3.1.0 # Календарь
  sqflite: ^2.3.0+1 # Локальная база данных SQLite
  path: ^1.9.0 # Работа с путями файлов
  shared_preferences: ^2.2.2 # Хранение ключ-значение
  flutter_markdown: ^0.7.1 # Отображение Markdown
  url_launcher: ^6.3.0 # Запуск URL
  tuple: ^2.0.2 # Кортежи для пар данных
  record: ^5.1.0 # Аудиозапись
  just_audio: ^0.9.39 # Аудиоплеер
  permission_handler: ^11.4.0 # Обработка разрешений
  path_provider: ^2.1.3 # Получение путей к файлам
  file_picker: ^9.0.2
  image_picker: ^0.8.7+5
  mime: ^1.0.4
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  effective_dart: ^1.3.2 # Анализ стиля кода

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic